FROM node:20.18

WORKDIR /usr/src/frontend

# 소스 코드 복사
COPY package.json package-lock.json* ./
RUN npm install

COPY . .
RUN npm run prisma:generate

# 개발용
# CMD ["npm", "run", "dev:docker"]

# 배포용
RUN npm install pm2 -g
RUN npm run build
CMD ["npm", "run", "deploy:docker"]
